export const categories = [
    {
        id: 1,
        name: "Rent",
    },
    {
        id:2,
        name:"Gas",
    },
    {
        id:3,
        name:"Mobile"
    },
    {
        id:4,
        name:"Internet"
    },
    {
        id:5,
        name:"Insurance"
    },
    {
        id:6,
        name:"Water"
    },
    {
        id:7,
        name:"Travel"
    },
    {
        id:8,
        name:"Market",
        Market:[
            {name:"Fruits"},
            {name:"Vegetables"},
            {name:"Cook"},
            {name:"Drinking"},
            {name:"JunkyFood"},
            {name:"Cleaning"}
        ]
    }
];